Enable the creation of external TableReferences
pydiverse/pydiverse.pipedag pull request #139
Opened 2024-02-24 17:57 UTC by nicolasmueller

Enable the creation of external TableReferences that reference tables in external schemas. This is useful to tell pipedag about tables that already exist in the database and should not be copied. It avoid manually reflecting them, which can sometimes be cumbersome as one might want to call a `Task` with a pipedag `Table` and sometimes with an external table.

# Checklist

- [ ] Added a `docs/source/changelog.md` entry

2024-02-26 23:50 UTC, NicolasMuellerQC commented
Enabling external views for DuckDB depends on https://github.com/duckdb/duckdb/issues/10322

2024-02-27 08:27 UTC, windiana42 commented
> Enabling external views for DuckDB depends on https://github.com/duckdb/duckdb/issues/10322

We could implement a workaround since this problem is quite common among some SQLAlchemy backends. We have such a workaround in other places of the codebase.

2024-02-27 09:27 UTC, windiana42 requested changes

2024-02-27 09:27 UTC, windiana42 commented on src/pydiverse/pipedag/backend/table/sql/sql.py
> +            return Table(TableReference("external_schema"), "name_of_table")
We might rename TableReference since it is tied to external and we might forbid the use of the name != None in dag.Table.
```suggestion
            return Table(ExternalTableReference("name_of_table", schema="external_schema"))
```

2024-02-29 10:41 UTC, nicolasmueller commented
>We could implement a workaround since this problem is quite common among some SQLAlchemy backends. We have such a workaround in other places of the codebase.

Done.

2024-02-29 17:13 UTC, nicolasmueller commented on src/pydiverse/pipedag/backend/table/sql/hooks.py
> +                schema=store.get_schema(tbl.stage.current_name, tbl).get(),
A DB2 test has been added in a5769bc701d276cf346e86d17526ffd408313890

2024-03-01 13:44 UTC, NicolasMuellerQC commented
@windiana42 Let me know if it looks good now 😃

2024-03-07 09:46 UTC, windiana42 commented on src/pydiverse/pipedag/backend/table/sql/ddl.py
> +            if tbl["shared_lock_allowed"]
Just to remind myself: this is needed to prevent DB2 dialect from locking external table reference input tables if not allowed.

2024-03-07 12:09 UTC, windiana42 approved these changes
Looks good to me (I changed a few things directly on the branch).

2024-03-07 12:46 UTC, nicolasmueller commented on src/pydiverse/pipedag/util/json.py
> +        tbl.shared_lock_allowed = d.get("shared_lock_allowed", False)
@windiana42 
This would change the default behavior for existing DB2 pipedag instances even for non-external tables (even though the shared locks are not currently working due to the bug fixed in #144 ) to not lock source tables (since the metadata `shared_lock_allowed` is not available there yet). 

I think the default here should be `True` as it is here:

https://github.com/pydiverse/pydiverse.pipedag/blob/ae1fd3614933972f6971699a107a2b7739624b3e/src/pydiverse/pipedag/materialize/container.py#L60

2024-03-07 13:01 UTC, windiana42 commented on src/pydiverse/pipedag/util/json.py
> +        tbl.shared_lock_allowed = d.get("shared_lock_allowed", False)
Correct. I only wanted the default to be False for ExternalTableReferences.

2024-03-07 13:01 UTC, windiana42 commented on src/pydiverse/pipedag/util/json.py
> +        tbl.shared_lock_allowed = d.get("shared_lock_allowed", False)
```suggestion
        tbl.shared_lock_allowed = d.get("shared_lock_allowed", True)
```

2024-03-07 13:03 UTC, windiana42 commented
@nicolasmueller good catch! did you find something else?

2024-03-07 13:11 UTC, NicolasMuellerQC commented
>@nicolasmueller good catch! did you find something else?

@windiana42  No, I am fine with merging then 👍

2024-03-07 13:43 UTC, merged