Refactor DB2 dependency in generic code.
pydiverse/pydiverse.pipedag pull request #158
Opened 2024-03-18 11:43 UTC by windiana42

Polymorphism is used instead.

# Checklist

- [x] Added a `docs/source/changelog.md` entry

2024-03-18 11:44 UTC, windiana42 commented
@nicolasmueller I prefer the polymorphism solution to getting rid of the DB2 dependency in generic code

2024-03-18 19:46 UTC, nicolasmueller requested changes
Currently the signature of `get_create_table_suffix` is inconsistent:
The generic table takes `table: Table` while the DB2 version takes `get_create_table_suffix: str | None`.
So either we have to adjust the generic version or fold `resolve_materialization_details_label` into the DB2 version.

I'd be in favor of the first version since the function is used without `resolve_materialization_details_label` in `copy_raw_sql_tables_to_transaction`.

2024-03-20 10:07 UTC, windiana42 commented
> Currently the signature of `get_create_table_suffix` is inconsistent: The generic table takes `table: Table` while the DB2 version takes `get_create_table_suffix: str | None`. So either we have to adjust the generic version or fold `resolve_materialization_details_label` into the DB2 version.
> 
> I'd be in favor of the first version since the function is used without `resolve_materialization_details_label` in `copy_raw_sql_tables_to_transaction`.

Oops. Yes the idea to simplify usage by just providing a table object is more tricky. So I went back to the old interface. One could consider to have take `Table | Stage` . I would think this is nicer encapsulation. But not nice enough to refactor it now.

2024-03-20 13:30 UTC, NicolasMuellerQC approved these changes
Looks good now!

2024-03-20 13:36 UTC, merged