Support nullable and non_nullable parameters in pipedag.Table() and refactor ddl/table-store/hook logic
pydiverse/pydiverse.pipedag pull request #160
Opened 2024-03-19 17:17 UTC by windiana42

The initial idea of this PR is to add a nullable and non_nullable parameter to pipedag.Table(). It should allow specifying nullability both positive and negative. For most dialects it is beneficial to create an empty table, then set nullability, and finally fill the table.

This PR turned into a somewhat bigger refactoring. DB2 had some create empty table and then fill it logic in DDL code, but if it is not a single dialect, I prefer such complex control in the hook and table store code. Also the generic/specific split of how derived classes can customize the generic algorithm was redesigned.

# Checklist

- [ ] Added a `docs/source/changelog.md` entry

2024-03-19 17:18 UTC, windiana42 commented
@NMAC427 FYI: a bigger refactoring of moving logic between DDL, table store, and hook is included in this PR

2024-03-20 15:15 UTC, NMAC427 requested changes

2024-03-20 15:15 UTC, NMAC427 commented on src/pydiverse/pipedag/backend/table/sql/sql.py
> +        return nullable_cols, non_nullable_cols
Can't this entire function be written in terms of set operations:
```python
nullable_cols = set(table.nullable or [])
non_nullable_cols = set(table.non_nullable or [])
table_cols = set(table_cols)

if invalid_cols := (nullable_cols | non_nullable_cols) - table_cols:
    raise ValueError(f"The columns {invalid_cols} aren't contained in the table")

if nullable_cols and non_nullable_cols:
    # If both are specified, they aren't allowed to intersect and
    # their union must be the set of all columns.
    if intersection := nullable_cols & non_nullable_cols:
        raise ValueError(f"The columns {intersection} are both set to be nullable and non nullable.")
    if missing_cols := table_cols - nullable_cols - non_nullable_cols:
        raise ValueError(
            "When setting both nullable and non_nullable, they must contain all table columns. "
            f"Missing columns: {missing_cols}"
        )
elif nullable_cols:
    non_nullable_cols = table_cols - nullable_cols
else:
    nullable_cols = table_cols - non_nullable_cols

return non_nullable_cols, nullable_cols
```

2024-03-20 15:16 UTC, NMAC427 commented on src/pydiverse/pipedag/backend/table/sql/sql.py
> +            if new_cols is not None:
(This should be addressed by the last review comment)

2024-03-20 16:48 UTC, windiana42 commented on src/pydiverse/pipedag/backend/table/sql/sql.py
> +    def format_sql_string(query_str: str, query=None, heavy_shorten_print=False) -> str:
In fact you are right that I did not find a good use for query. I was a bit concerned we would lose relevant information during query rendering that might be useful for shortening, but in fact I couldn't use it.

truncate_select is also more correct to what is actually implemented. The idea was to keep the kind of shortening open to more implementation alternatives that might be still configurable. For example one could just cut the select columns but keep the FROM part in case it does not exceed a certain size.

I will encorporate your suggestions. For now, they are better.

2024-03-20 16:49 UTC, windiana42 commented on src/pydiverse/pipedag/backend/table/sql/sql.py
> +        transaction_already_open=False,
I will check. I was struggling to find this programmatically.

2024-03-20 16:50 UTC, windiana42 commented on src/pydiverse/pipedag/backend/table/sql/sql.py
> +        hook.materialize(self, dest_tbl, dest_tbl.stage.transaction_name)
CopyTable is still used in copying tables for cache valid RawSQL statements. We could also get rid of it there. But there, we would need to fabricate artificial dag.Table objects. That is not that nice either. So I would keep it for now.

2024-03-20 16:53 UTC, windiana42 commented on src/pydiverse/pipedag/backend/table/sql/sql.py
> +            if new_cols is not None:
The extreme of your idea would be 
`for new_cols, is_nullable in [(cols,flag) for cols,flag in zip(
            [table.nullable, table.non_nullable], [True, False]
        ) if cols is not None]:`

2024-03-20 16:56 UTC, windiana42 commented on src/pydiverse/pipedag/backend/table/sql/sql.py
> +    ) -> tuple[list[str], list[str]]:
Yes, it is used a bit comfuscated. It returns the columns that should be forced nullable or non-nullable. This is mainly driven by fields table.nullable and table.non_nullable. But it is also determined by dialect specific aspects whether nullable fields need to be forced at all and whether primary_key columns should be explicitly forced non-nullable. If the dialect also modifies the type of primary key columns it will not be included here because this needs to be done separately anyways.

How about changing the name to `get_forced_nullability_columns`?

2024-03-20 16:58 UTC, windiana42 commented on src/pydiverse/pipedag/backend/table/sql/sql.py
> +        return nullable_cols, non_nullable_cols
As far as I know, sets are unordered even if dicts are ordered these days. In fact, the ordering is not super important, but helps humas to understand what is going on in an already complex process.

2024-03-20 17:00 UTC, windiana42 commented on src/pydiverse/pipedag/backend/table/sql/sql.py
> +        return nullable_cols, non_nullable_cols
I am sure I can still produce something nicer in line with your proposal.

2024-03-20 17:04 UTC, windiana42 commented on src/pydiverse/pipedag/backend/table/sql/sql.py
> +        return nullable_cols, non_nullable_cols
`if nullable_cols and non_nullable_cols` cannot distinguish between None and [] which does make a difference in the input. I need the implementation of the report_nullable_cols flag for dialects which like to reuse this algorithm. However, I could also solve this with an additional function name. And I might still consider to order outputs first by table.[non_]nullable and then by table_cols at the end.

2024-03-20 17:19 UTC, windiana42 commented on src/pydiverse/pipedag/backend/table/sql/sql.py
> +            def begin():
```python
            @contextmanager
            def transactional():
                if conn.in_transaction():
                    yield
                else:
                    with conn.begin():
                        yield

            with transactional():
```

2024-03-20 18:06 UTC, windiana42 commented on src/pydiverse/pipedag/backend/table/sql/sql.py
> +        return nullable_cols, non_nullable_cols
I prefer your style and made it return better error messages. But it is not shorter anymore:
```python
    @staticmethod
    def _process_table_nullable_parameters(table: Table, table_cols: Iterable[str]):
        name = f'"{table.name}"'
        nullable_set = set(table.nullable or [])
        non_nullable_set = set(table.non_nullable or [])
        table_cols_set = set(table_cols)

        for prefix, col_set, cols in [
            ("", nullable_set, table.nullable),
            ("non_", non_nullable_set, table.non_nullable)
        ]:
            if invalid_cols := col_set - table_cols_set:
                raise ValueError(
                    f"The columns {invalid_cols} in Table({name},"
                    f" {prefix}nullable={cols}) aren't contained in the table"
                    f" columns: {table_cols}"
                )

        if table.nullable is not None and table.non_nullable is not None:
            # If both are specified, they aren't allowed to intersect and
            # their union must be the set of all columns.
            if intersection := nullable_set & non_nullable_set:
                raise ValueError(
                    f"The columns {intersection} are both set to be nullable and non"
                    f" nullable in Table({name}, nullable={table.nullable},"
                    f" non_nullable={table.non_nullable})")
            if missing_cols := table_cols_set - nullable_set - non_nullable_set:
                raise ValueError(
                    f"When setting Table({name}, nullable={table.nullable},"
                    f" non_nullable={table.non_nullable}), all columns of the"
                    f" table must be mentioned. Missing columns: {missing_cols}"
                )
            nullable = table.nullable
            non_nullable = table.non_nullable
        elif table.nullable is not None:
            non_nullable = [c for c in table_cols if c not in nullable_set]
            nullable = table.nullable
        elif table.non_nullable is not None:
            nullable = [c for c in table_cols if c not in non_nullable_set]
            non_nullable = table.non_nullable
        else:
            nullable = []
            non_nullable = []

        return nullable, non_nullable
```

2024-03-20 18:14 UTC, windiana42 commented on src/pydiverse/pipedag/backend/table/sql/sql.py
> +    ) -> tuple[list[str], list[str]]:
```python
    def get_forced_nullability_columns(
        self, table: Table, table_cols: Iterable[str]
    ) -> tuple[list[str], list[str]]:
        """
        Get the columns that should be forced to be nullable or non-nullable.

        This is typically applied on the materialized empty table, but may also
        be applied after filling the table by some dialects. Some dialects may
        choose to add primary key columns to non_nullable_cols if they need it
        to set the primary key. However, some dialects do this separately because
        they also need to change the type of primary key columns. Some dialects
        only return non-nullable columns because all columns will be nullable
        after initial materialization.

        :param table:
            Table to be materialized. It includes attributes like nullable,
            non_nullable, and primary_key which may influence the return value.
        :param table_cols:
            The list of all columns in the table. If nullable and non_nullable is
            specified, all columns must be mentioned. If only one of them is set,
            the other one is calculated as the remaining set.
        :return:
            A tuple of two lists. The first list contains the columns that should
            be forced to be nullable, the second list contains the columns that
            should be forced to be non-nullable. Most dialects will not need to
            force nullable columns because very column is nullable by default.
        """
        _, non_nullable_cols = self._process_table_nullable_parameters(table, table_cols)

        # in most dialects columns are nullable by default
        return [], non_nullable_cols
```

2024-03-21 16:25 UTC, windiana42 commented
@NMAC427 can you please confirm that the requested changes are completed?

2024-03-25 10:14 UTC, merged