feat(): add truncation of primary keys and indexes
pydiverse/pydiverse.pipedag pull request #201
Opened 2024-06-18 07:57 UTC by DominikZuercherQC

MSSQL does not allow identifiers longer than 128 characters. 
Similarly, postgres automatically truncates identifiers at 63 characters.
This PR automatically truncates all primary key and index identifiers at 63 characters.

# Checklist

- [ ] Added a `docs/source/changelog.md` entry
- [ ] Added/updated documentation in `docs/source/`
- [ ] Added/updated examples in `docs/source/examples.md`

2024-07-10 15:03 UTC, windiana42 requested changes

2024-07-10 15:03 UTC, windiana42 commented on src/pydiverse/pipedag/backend/table/sql/ddl.py
> +            prefix + str(hash(table_name.lower() + columns))[: max_length - len(prefix)]
I think this is dangerous for collisions. I would reserve a certain number of characters for a hash. Then you can truncate the table name and append the hash here.

2024-07-10 15:03 UTC, windiana42 commented on src/pydiverse/pipedag/backend/table/sql/ddl.py
> +        col_hash = str(hash(table_name.lower() + columns))
It might be important to use a stable hash here. hash() changes from run to run. We have a utility function called stable_hash in pipedag.

2024-07-18 05:05 UTC, DominikZuercherQC commented on src/pydiverse/pipedag/backend/table/sql/ddl.py
> +        col_hash = str(hash(table_name.lower() + columns))
Thanks I was not aware that hash() is not constant over runs. Using stable_hash() now.

2024-07-18 05:22 UTC, DominikZuercherQC commented on src/pydiverse/pipedag/backend/table/sql/ddl.py
> +            prefix + str(hash(table_name.lower() + columns))[: max_length - len(prefix)]
I changed the logic a bit such that the hash is used first

2024-07-18 14:12 UTC, windiana42 approved these changes
Nice!

2024-07-18 14:12 UTC, windiana42 commented on src/pydiverse/pipedag/backend/table/sql/ddl.py
> +MAX_LENGTH_INDEX = 63
It would be nice to have an issue that talks about making this configurable as argument to the SQLTableStore. This could even be labeled "good first issue".

2024-07-18 14:40 UTC, merged