Fix polars >= 1
pydiverse/pydiverse.pipedag pull request #212
Opened 2024-07-31 15:09 UTC by nicolasmueller

Currently retrieving a polars dataframe with polars 1.2 crashes. This is because we currently use `read_database` instead of `read_database_uri`, but hand it a URI. My guess is that polars 1 got stricter with it's behavior.

# Checklist

- [ ] Added a `docs/source/changelog.md` entry
- [ ] Added/updated documentation in `docs/source/`
- [ ] Added/updated examples in `docs/source/examples.md`

2024-07-31 18:35 UTC, QuantCo-mr-T approved these changes

2024-07-31 18:35 UTC, QuantCo-mr-T commented on tests/test_table_hooks/test_polars.py
> +            df = pl.read_database_uri(query, connection_uri)
Are we sure there is a Polars version for python 3.9 which offers the read_database_uri function?

2024-07-31 18:37 UTC, QuantCo-mr-T commented on tests/test_table_hooks/test_polars.py
> +            df = pl.read_database_uri(query, connection_uri)
Potentially we have to change the Polars version dependency constraint to ensure the read_database_uri function exists

2024-08-01 13:16 UTC, windiana42 requested changes
Please update dependencies to 'polars >= 0.19'

2024-08-01 13:16 UTC, windiana42 commented on tests/test_table_hooks/test_polars.py
> +            df = pl.read_database_uri(query, connection_uri)
We still need to require polars >= 0.19. But this should be fine since it support python 3.9: https://prefix.dev/channels/conda-forge/packages/polars

2024-08-06 12:30 UTC, windiana42 approved these changes

2024-08-06 14:24 UTC, merged